version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: streamtube-mongodb
    restart: unless-stopped
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db

  app:
    build: .
    container_name: streamtube-backend
    depends_on:
      - mongodb
    ports:
      - '8000:8000'
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - PORT=8000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run dev
